backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "pages"
    label: "Page Data"
    files:
      - name: "gig_list_data"
        label: "Gig List Page"
        file: "data/gig-list.json"
        fields:
          - label: "All Gigs"
            name: "gigs"
            widget: "list"
            summary: "{{fields.date}} - {{fields.band}}"
            fields:
              - { label: "Date (e.g. 16/01)", name: "date", widget: "string" }
              - { label: "Band Name", name: "band", widget: "string" }
              - { label: "Description", name: "desc", widget: "string" }
              - { label: "Price Info", name: "price", widget: "string", default: "Â£10 Door" }

      - name: "ticket_data"
        label: "Tickets Page"
        file: "data/tickets.json"
        fields:
          - label: "Available Tickets"
            name: "tickets"
            widget: "list"
            summary: "{{fields.band}} ({{fields.full_date}})"
            fields:
              - { label: "Band Name", name: "band", widget: "string" }
              - { label: "Full Date (e.g. 23/01/2026)", name: "full_date", widget: "string" }
              - { label: "Ticket Link (URL)", name: "link", widget: "string" }

      - name: "homepage"
    label: "Homepage Hero"
    files:
      - file: "content/hero.json"
        label: "Hero Section"
        name: "hero"
        fields:
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Hero Image", name: "image", widget: "image"}
          - {label: "Description Text", name: "body", widget: "text"}
